import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

const Garamond = localFont({ src: '../../public/AGaramondPro-Regular.otf' });
const Akkurat = localFont({ src: '../../public/Akkurat.ttf' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body className={Garamond.className}>
        {children}
      </body>
    </html>
  )
}
